@startuml
!include <C4/C4_Component>

Container_Boundary(backend, "Микросервисный бэкенд", "Управляет умными устройствами") {   
    Component(api_getway, "Getway", "API Getway Kong")   
    Component(broker, "Брокер сообщений", "Брокер сообщений Kafka")
    
    Component(temperature_manager, "Компонент мониторинга температуры")
    Component(temperature_db, "БД мониторинга температуры")

    Component(heat_manager, "Компонент управления отоплением")
    Component(heat_db, "БД управления отоплением")

    Component(light_manager, "Компонент управления светом")
    Component(light_db, "БД управления светом")

    Component(gate_manager, "Компонент управления воротами")
    Component(gate_db, "БД управления воротами")

    Component(camera_manager, "Компонент управления камерами")
    Component(camera_db, "БД управления камерами")

    Component(user_manager, "Компонент управления пользователями")
    Component(user_db, "БД управления пользователями")
    
    Component(bff, "Компонент backend for frontend")  
}
Container_Ext(frontend, "Web интерфейс для управление умными устройствами", "", "Интерфейс для управления и добавления новых устройств пользователем")
Container(admin_frontend, "Web интерфейс для техподдержки", "React", "Позволяет обеспечивать поддержку клиентов. Чтение логов, мониторинг системы, создание задач на обработку ошибок и т.д.")
System_Ext(sensor1, "Система мониторинга температуры")
System_Ext(sensor2, "Система отопления")
System_Ext(sensor3, "Система управления светом")
System_Ext(sensor4, "Система управления воротами")
System_Ext(sensor5, "Система управления камерами")

Rel(broker, api_getway, "Маршрутизация сообщений")

Rel(frontend, api_getway, "Передача команд для управления устройствами")
Rel(admin_frontend, api_getway, "Передача команд для администрации")

Rel(api_getway, temperature_manager, "Маршрутизация запросов")
Rel(temperature_manager, temperature_db, "")
Rel(temperature_manager, sensor1, "Считывает данных о температуре")

Rel(api_getway, heat_manager, "Маршрутизация запросов")
Rel(heat_manager, heat_db, "")
Rel(heat_manager, sensor2, "Регулирование отопления")
Rel(heat_manager, broker, "Запрос данных о температуре")

Rel(api_getway, light_manager, "Маршрутизация запросов")
Rel(light_manager, light_db, "")
Rel(light_manager, sensor3, "Включение и отключение света")

Rel(api_getway, gate_manager, "Маршрутизация запросов")
Rel(gate_manager, gate_db, "")
Rel(gate_manager, sensor4, "Открытие и закрытие ворот")

Rel(api_getway, camera_manager, "Маршрутизация запросов")
Rel(camera_manager, camera_db, "")
Rel(camera_manager, sensor5, "Трансляции видео от камер")

Rel(api_getway, user_manager, "Маршрутизация запросов")
Rel(api_getway, user_manager, "Авторизация пользователей")
Rel(user_manager, user_db, "")

Rel(api_getway, bff, "Маршрутизация запросов")
Rel(bff, broker, "Запрос на сбор данных для frontend")

@enduml