@startuml
!include <C4/C4_Container>

Person(client, "Клиент", "")
Person(admin, "Служба поддержки", "")
System_Ext(sensor1, "Датчики мониторинга температуры")
System_Ext(sensor2, "Датчики отопления")
System_Ext(sensor3, "Датчики управления светом")
System_Ext(sensor4, "Датчики управления воротами")
System_Ext(sensor5, "Датчики управления камерами")
System_Boundary(service, "Сервис удаленного управления", "Набор микросервисов управляющий умными устройствами") {
    Container_Ext(frontend, "Web интерфейс для управление умными устройствами", "", "Интерфейс для управления и добавления новых устройств пользователем")
    Container(admin_frontend, "Web интерфейс для техподдержки", "React", "Позволяет обеспечивать поддержку клиентов. Чтение логов, мониторинг системы, создание задач на обработку ошибок и т.д.")
    Container(backend, "Микросервисный бэкенд", "Java", "Управляет умными устройствами")
}

Rel(client, frontend, "Использует")
Rel(admin, admin_frontend, "Администрирует")
Rel(backend, sensor1, "Считывает данных о температуре")
Rel(backend, sensor2, "Регулирование отопления")
Rel(backend, sensor3, "Включение и отключение света")
Rel(backend, sensor4, "Открытие и закрытие ворот")
Rel(backend, sensor5, "Трансляции видео от камер")
Rel(frontend, backend, "Передача команд для управления устройствами")
Rel(admin_frontend, backend, "Передача команд для администрации")

@enduml